test(fd_cache): make tests self-contained, and enable in CI (#276)
The previous commit [1] added testament-based unit testing, but didn't
migrate the fd_cache tests because they relied on files to be manually
created. On `main`, we would see the error:

    $ nim r src/fd_cache.nim
    fatal.nim(53)            sysFatal
    Error: unhandled exception: fd_cache.nim(272, 11) `one1 != two`  [AssertionDefect]

Make those tests self-contained, and migrate them to the new
testament-based system so they now run in CI.

Also prefer `doAssert` as Nim itself recommends [2], and use `{.all.}`
to avoid adding the export marker in source files only for testing
purposes. From the Nim 1.6.0 release post [3]:

    A new import syntax `import foo {.all.}` now allows importing all
    symbols (public or private) from foo. This can be useful for testing
    purposes or for more flexibility in project organization.

Closes: https://github.com/crashappsec/chalk/issues/275

[1] 46ffecdfff56, 2024-04-26, "ci: add testament-based unit testing"
[2] https://nim-lang.org/2.0.0/contributing.html#writing-tests-stdlib
[3] https://nim-lang.org/blog/2021/10/19/version-160-released.html#private-imports-and-private-field-access