ci(unit-tests): add docker/setup-buildx-action and docker/login-action
Copy steps from tests.yml, trying to fix error:

    ERROR: Cache export is not supported for the docker driver.
    Switch to a different driver, or turn on the containerd image store, and try again.
    Learn more at https://docs.docker.com/go/build-cache-backends/
    Error: Process completed with exit code 1.