feat: allow bypassing chalk via CHALK_BYPASS environment variable
A sketch of a possible implementation for bypassing chalk.

It allows bypassing the exec command:

    $ CHALK_BYPASS=1 ./chalk exec echo hi
    chalk: the CHALK_BYPASS environment variable is set.
    Running the following command without chalk:
      echo hi
    hi

and bypassing the docker command:

    $ CHALK_BYPASS=1 ./chalk docker --version
    chalk: the CHALK_BYPASS environment variable is set.
    Running the following command without chalk:
      docker --version
    Docker version 25.0.3, build 4debf411d1

and errors when the command is not docker or exec:

    $ CHALK_BYPASS=1 ./chalk version
    error: CHALK_BYPASS was set, but the chalk command is not 'docker' or 'exec'. Quitting.