fix(docker): fixing flaky heartbeat test
The root cause was that probe build to get current build platform,
docker tag name was random which sometimes resulted in invalid tag
names:

```
ERROR: invalid tag ".mpiljfkim.ahsfgpf3f4g": invalid reference format
```

docker tag names need to start/end with alphanumeric character so to
solve it adding "chalk_" and `_probe" prefix/suffix. This ensures the
build tag is correct and docker can build it.