test: fixing flaky test (#405)
looks like in some cases tmp file was garbage collected earlier than the
process exit which resulted in :

```
ERROR: failed to solve: failed to read dockerfile: open tmp_76z0fet: no such file or directory
```

passing content as stdin should make that irrelevant however if well
need to do any contextual cleanup as part of cmd handling also moved it
as a context manager which will allow us to cleanup anything necessary
after the full command is finished executing

also in some cases stderr did not match between the commands as it
included the failure timestamp so no longer comparing it as part of the
program equality logic