fix: semgrep needs to be on PATH
starting with 1.94.0, if semgrep is not on PATH, its not able to run and
throws:

```
Error: exception Unix_error: No such file or directory execvp pysemgrep
```