disabling secretmanager for setup test (#701)
secret manager is now a protected endpoint which is why test is failing:

```
error: When attempting to save signing secret: 401 Unauthorized
error: Could not store password. Either try again later, or use the below
       password with the CHALK_PASSWORD environment variable. We attempt to
       store as long as use_secret_manager is true.
```