fix(heartbeat): fixing flaky heartbeat test due to invalid probe build tag (#45)
* fix(docker): fixing flaky heartbeat test

The root cause was that probe build to get current build platform,
docker tag name was random which sometimes resulted in invalid tag
names:

```
ERROR: invalid tag ".mpiljfkim.ahsfgpf3f4g": invalid reference format
```

docker tag names need to start/end with alphanumeric character so to
solve it adding "chalk_" and `_probe" prefix/suffix. This ensures the
build tag is correct and docker can build it.

* test(docker): allowing log_level arg to docker_build

* test(heartbeat): heartbeat test with trace log level

this test case is flaky so adding trace log level hopefully will help
to diagnose the issue further

in addition as in case cases trace log will include reports internally
adjusting report parsing logic to ignore any log lines which should
only find valid json reports in the output

* doc(release): adding release note for wrap entrypoint fix

also fixing spelling typos in rest of the doc

* refactor: using common chooseNewTag everywhere for docker build