adding .sha256 checksums to release pipeline (#656)
* adding .sha256 checksums to release pipeline

moving the alias logic to Makefile which allows github
to simply sync dist folder with s3

* allowing to execute dist on mac

on mac sha256sum is not available by default
it can be installed with brew however by default
mac has shasum command where you need to use
-a arg to switch sha algorithm

* buildx setup is required on all runners

otherwise getting:

```
ERROR: Cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

* fix: signing in into github container registry in order

this will allow release job to pull container cache

* adding aarch64 alias if uname -m returns arm64

* using common makefile for making dist for server/chalk

this avoid duplicating same release logic in both

* splitting dist lowercase/normalcase in diff folders

some FS are case-insensitive and so cannot duplicate
filenames for easy upload

* fixing current-version.txt dist

* binary might not exist yet in server/Makefile